from ml_method_reports.reporting.adapters import ReportType
from ml_method_reports.reporting.api import report_for
from ml_method_reports.reporting.builders import (
    AgglomerativeReportBuilder,
    AgglomerativeReportInput,
    DecisionTreeReportBuilder,
    DecisionTreeReportInput,
    EtalonReportBuilder,
    EtalonReportInput,
    EtalonRun,
    GenericClassificationReportBuilder,
    KMeansReportBuilder,
    KMeansReportInput,
    KnnReportBuilder,
    KnnReportInput,
    LogisticRegressionReportBuilder,
    LogisticRegressionReportInput,
    RandomForestReportBuilder,
    RandomForestReportInput,
    ReportAssetBuilder,
    ReportBuilder,
    SvcReportBuilder,
    SvcReportInput,
    build_analysis_summary,
)
from ml_method_reports.reporting.context import ReportContext
from ml_method_reports.reporting.html_report import (
    HtmlReportGenerator,
    build_supervised_experiment_report,
)
from ml_method_reports.reporting.models import ExperimentReport, ReportSection
from ml_method_reports.reporting.notebook import display_report, render_notebook_html
from ml_method_reports.reporting.pdf_report import PdfExperimentReportGenerator
from ml_method_reports.reporting.plots import (
    plot_bar_chart,
    plot_cluster_projection,
    plot_etalon_decision_space,
    plot_full_vs_one_feature_comparison,
    plot_knn_neighbor_space,
    plot_model_accuracy_comparison,
    project_to_2d,
)
from ml_method_reports.reporting.serialization import (
    format_report_value,
    sanitize_table_rows,
    to_report_value,
)
from ml_method_reports.reporting.types import (
    FeatureMatrix,
    PathLike,
    PredictionVector,
    PredictiveModel,
    ReportBuilderObject,
    ReportMetadata,
    ReportOptions,
    TableRow,
    TableRows,
    TargetVector,
)

__all__ = [
    "AgglomerativeReportBuilder",
    "AgglomerativeReportInput",
    "DecisionTreeReportBuilder",
    "DecisionTreeReportInput",
    "EtalonReportBuilder",
    "EtalonReportInput",
    "EtalonRun",
    "ExperimentReport",
    "FeatureMatrix",
    "GenericClassificationReportBuilder",
    "HtmlReportGenerator",
    "KMeansReportBuilder",
    "KMeansReportInput",
    "KnnReportBuilder",
    "KnnReportInput",
    "LogisticRegressionReportBuilder",
    "LogisticRegressionReportInput",
    "PathLike",
    "PdfExperimentReportGenerator",
    "PredictionVector",
    "PredictiveModel",
    "RandomForestReportBuilder",
    "RandomForestReportInput",
    "ReportAssetBuilder",
    "ReportBuilder",
    "ReportBuilderObject",
    "ReportContext",
    "ReportMetadata",
    "ReportOptions",
    "ReportSection",
    "ReportType",
    "SvcReportBuilder",
    "SvcReportInput",
    "TableRow",
    "TableRows",
    "TargetVector",
    "build_analysis_summary",
    "build_supervised_experiment_report",
    "display_report",
    "format_report_value",
    "plot_bar_chart",
    "plot_cluster_projection",
    "plot_etalon_decision_space",
    "plot_full_vs_one_feature_comparison",
    "plot_knn_neighbor_space",
    "plot_model_accuracy_comparison",
    "project_to_2d",
    "report_for",
    "render_notebook_html",
    "sanitize_table_rows",
    "to_report_value",
]
